name: Toolforge Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Run deploy.sh
        run: |
          ssh ${{ secrets.SSH_USER }}@login.toolforge.org \
          become qs-dev ./www/python/deploy.sh
